### ISSUE TITLE
images not showing up in documentation page

### ISSUE THREAD

**Issue by pieper** [HOA-2/SlicerNeuroSegmentation#24]
This page is linked from the main readme but the image links are broken:

https://github.com/HOA-2/SlicerNeuroSegmentation/blob/main/docs/General%20Segmentation.md

**Comment by Sunderlandkyl** [comment]
Thanks Steve! The old manual has been deprecated, although there should be a new one made available once the associated  paper has been published.

I've removed old manual from the repository.
